/* eslint-disable @typescript-eslint/no-empty-object-type -- declaration merging augments generated Worker types */
// Optional secrets are configured only when the owner enables Web Push.
// Cloudflare bindings and ordinary vars remain generated by `wrangler types`.
interface OptionalPushSecrets {
  VAPID_PUBLIC_KEY?: string;
  VAPID_PRIVATE_KEY?: string;
  VAPID_SUBJECT?: string;
}
declare namespace Cloudflare {
  interface Env extends OptionalPushSecrets {}
}
interface Env extends OptionalPushSecrets {}
